"""Tests for undercover mode — sanitize_message strips AI codenames."""


# ---------------------------------------------------------------------------
# Model name / codename removal
# ---------------------------------------------------------------------------

def test_sanitize_removes_claude_model_names():
    from agent.undercover import sanitize_message
    msg = "Built with claude-sonnet and claude-opus"
    result = sanitize_message(msg)
    assert "claude-sonnet" not in result
    assert "claude-opus" not in result


def test_sanitize_removes_claude_haiku():
    from agent.undercover import sanitize_message
    msg = "Powered by claude-haiku for fast responses"
    result = sanitize_message(msg)
    assert "claude-haiku" not in result


def test_sanitize_removes_internal_codenames():
    from agent.undercover import sanitize_message
    msg = "Internal model Tengu was used for this task"
    result = sanitize_message(msg)
    assert "Tengu" not in result


def test_sanitize_removes_opus_codename():
    from agent.undercover import sanitize_message
    msg = "Model Opus answered the question"
    result = sanitize_message(msg)
    assert "Opus" not in result


def test_sanitize_removes_sonnet_codename():
    from agent.undercover import sanitize_message
    msg = "Sonnet generated this summary"
    result = sanitize_message(msg)
    assert "Sonnet" not in result


def test_sanitize_removes_haiku_codename():
    from agent.undercover import sanitize_message
    msg = "Used Haiku for quick tasks"
    result = sanitize_message(msg)
    assert "Haiku" not in result


def test_sanitize_removes_claude_code_name():
    from agent.undercover import sanitize_message
    msg = "Generated by claude-code toolchain"
    result = sanitize_message(msg)
    assert "claude-code" not in result


def test_sanitize_removes_claude_code_proper_noun():
    from agent.undercover import sanitize_message
    msg = "Claude Code was used to implement this feature"
    result = sanitize_message(msg)
    assert "Claude Code" not in result


def test_sanitize_removes_shadowdev_ai():
    from agent.undercover import sanitize_message
    msg = "ShadowDev AI assisted with the refactor"
    result = sanitize_message(msg)
    assert "ShadowDev AI" not in result


# ---------------------------------------------------------------------------
# Co-Authored-By / email removal
# ---------------------------------------------------------------------------

def test_sanitize_removes_co_authored_by_line():
    from agent.undercover import sanitize_message
    msg = "Fix bug\n\nCo-Authored-By: Claude Sonnet <noreply@anthropic.com>"
    result = sanitize_message(msg)
    assert "anthropic.com" not in result


def test_sanitize_removes_anthropic_email():
    from agent.undercover import sanitize_message
    msg = "Contact: noreply@anthropic.com for support"
    result = sanitize_message(msg)
    assert "anthropic.com" not in result


def test_sanitize_removes_generated_by_claude():
    from agent.undercover import sanitize_message
    msg = "Generated by Claude in 3 seconds"
    result = sanitize_message(msg)
    assert "Generated by Claude" not in result


# ---------------------------------------------------------------------------
# Clean messages — content preservation
# ---------------------------------------------------------------------------

def test_sanitize_clean_message_unchanged():
    from agent.undercover import sanitize_message
    msg = "Fix null pointer exception in auth module"
    result = sanitize_message(msg)
    assert "null pointer" in result
    assert "auth module" in result


def test_sanitize_preserves_commit_prefix():
    from agent.undercover import sanitize_message
    msg = "feat: add user authentication flow"
    result = sanitize_message(msg)
    assert "feat:" in result
    assert "user authentication flow" in result


def test_sanitize_preserves_multiline_clean_message():
    from agent.undercover import sanitize_message
    msg = "fix: resolve race condition\n\nAdded mutex lock around shared state access."
    result = sanitize_message(msg)
    assert "race condition" in result
    assert "mutex lock" in result


# ---------------------------------------------------------------------------
# Return type and edge cases
# ---------------------------------------------------------------------------

def test_sanitize_returns_string():
    from agent.undercover import sanitize_message
    result = sanitize_message("some commit message")
    assert isinstance(result, str)


def test_sanitize_empty_string():
    from agent.undercover import sanitize_message
    result = sanitize_message("")
    assert result == ""


def test_sanitize_case_insensitive_for_codenames():
    """Word-boundary patterns are IGNORECASE — mixed case should also be stripped."""
    from agent.undercover import sanitize_message
    msg = "CLAUDE-SONNET was invoked"
    result = sanitize_message(msg)
    assert "CLAUDE-SONNET" not in result


def test_sanitize_replaces_with_ai_placeholder():
    """Removed terms are replaced with [AI], not deleted silently."""
    from agent.undercover import sanitize_message
    msg = "claude-sonnet answered"
    result = sanitize_message(msg)
    assert "[AI]" in result


def test_sanitize_multiple_codenames_all_removed():
    """All codenames in a single message are stripped."""
    from agent.undercover import sanitize_message
    msg = (
        "claude-opus and claude-haiku powered by Tengu "
        "Co-Authored-By: Claude <noreply@anthropic.com>"
    )
    result = sanitize_message(msg)
    assert "claude-opus" not in result
    assert "claude-haiku" not in result
    assert "Tengu" not in result
    assert "anthropic.com" not in result


# ---------------------------------------------------------------------------
# New codenames added in Sprint 13
# ---------------------------------------------------------------------------

def test_sanitize_removes_capybara_codename():
    from agent.undercover import sanitize_message
    msg = "Model Capybara was deployed"
    result = sanitize_message(msg)
    assert "Capybara" not in result


def test_sanitize_removes_orion_codename():
    from agent.undercover import sanitize_message
    msg = "Orion handled the request"
    result = sanitize_message(msg)
    assert "Orion" not in result


def test_sanitize_removes_openai_attribution():
    from agent.undercover import sanitize_message
    msg = "Co-Authored-By: GPT <noreply@openai.com>"
    result = sanitize_message(msg)
    assert "openai.com" not in result


def test_sanitize_removes_gpt_model_names():
    from agent.undercover import sanitize_message
    msg = "Built with gpt-4o for code generation"
    result = sanitize_message(msg)
    assert "gpt-4o" not in result


def test_sanitize_removes_generated_with_claude_code():
    from agent.undercover import sanitize_message
    msg = "🤖 Generated with [Claude Code](https://claude.ai)"
    result = sanitize_message(msg)
    assert "Claude Code" not in result


def test_sanitize_removes_powered_by_claude():
    from agent.undercover import sanitize_message
    msg = "Powered by Claude for AI assistance"
    result = sanitize_message(msg)
    assert "Powered by Claude" not in result
