"""
Undercover mode — strips internal AI model codenames and identifiers from
commit messages and PR descriptions when contributing to public repos.

Inspired by CC's undercover.ts — prevents accidental disclosure of AI tooling
in open-source contributions.
"""
import re

# ── Model codenames — internal project names that should never appear publicly ──
# Sourced from CC reference + common Anthropic/OpenAI internal aliases
_CODENAMES = [
    # Anthropic model series
    "claude-sonnet", "claude-opus", "claude-haiku",
    "claude-instant", "claude-v1", "claude-v2", "claude-v3",
    # Internal project codenames (from CC leak ref)
    "Tengu", "Capybara", "Orion", "Bedrock",
    # Model display names
    "Opus", "Sonnet", "Haiku",
    # Tool/product names
    "claude-code", "Claude Code", "ShadowDev AI", "ShadowDev",
    # Attribution strings
    "Generated by Claude", "Co-Authored-By: Claude",
    "Powered by Claude", "Built with Claude",
    # OpenAI equivalents (for multi-provider mode)
    "gpt-4o", "gpt-4-turbo", "o1-preview", "o1-mini",
    "Generated by GPT", "Co-Authored-By: GPT",
]

# Compile word-boundary patterns for most terms
_WORD_BOUNDARY_PATS = [
    re.compile(r'\b' + re.escape(c) + r'\b', re.IGNORECASE)
    for c in _CODENAMES
    if not c.startswith(("noreply", "Co-Authored"))
]

# Special patterns without word boundaries (emails, attribution lines)
_SPECIAL_PATS = [
    re.compile(r'noreply@anthropic\.com', re.IGNORECASE),
    re.compile(r'noreply@openai\.com', re.IGNORECASE),
    re.compile(r'Co-Authored-By:.*?(?:anthropic|openai|claude|gpt).*?(?:\n|$)', re.IGNORECASE),
    re.compile(r'🤖\s*Generated with \[?Claude Code\]?[^\n]*', re.IGNORECASE),
    re.compile(r'🤖\s*Generated with \[?ShadowDev\]?[^\n]*', re.IGNORECASE),
]

_ALL_PATTERNS = _WORD_BOUNDARY_PATS + _SPECIAL_PATS


def sanitize_message(text: str) -> str:
    """Remove internal AI model codenames from commit messages or PR descriptions.

    Replaces detected codenames with "[AI]" to avoid disclosing AI tooling
    in public repository contributions.

    Args:
        text: Commit message, PR title, or PR body to sanitize.

    Returns:
        Sanitized text with codenames replaced.
    """
    for pat in _ALL_PATTERNS:
        text = pat.sub("[AI]", text)
    return text.strip()
