"""
Undercover mode — strips internal AI model codenames and identifiers from
commit messages and PR descriptions when contributing to public repos.
"""
import re

# Known internal codenames to strip (expand as needed)
_CODENAMES = [
    "claude-sonnet", "claude-opus", "claude-haiku",
    "Tengu", "Opus", "Sonnet", "Haiku",
    "claude-code", "Claude Code", "ShadowDev AI",
    "Generated by Claude", "Co-Authored-By: Claude",
    r"noreply@anthropic\.com",
]

_PATTERNS = [re.compile(r'\b' + re.escape(c) + r'\b', re.IGNORECASE) for c in _CODENAMES
             if not c.startswith(r'noreply')]
# Special patterns without word boundaries
_PATTERNS.append(re.compile(r'noreply@anthropic\.com', re.IGNORECASE))
_PATTERNS.append(re.compile(r'Co-Authored-By:.*?anthropic.*?\n?', re.IGNORECASE))


def sanitize_message(text: str) -> str:
    """Remove internal codenames from commit messages or PR descriptions."""
    for pat in _PATTERNS:
        text = pat.sub("[AI]", text)
    return text.strip()
