# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tools.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tools.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btools.proto\x12\x07\x61gentic\"\x07\n\x05\x45mpty\"K\n\x0bToolRequest\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x02 \x01(\t\x12\x11\n\tworkspace\x18\x03 \x01(\t\"\\\n\x0cToolResponse\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x19\n\x11\x65xecution_time_ms\x18\x04 \x01(\x01\",\n\x08ToolList\x12 \n\x05tools\x18\x01 \x03(\x0b\x32\x11.agentic.ToolInfo\"$\n\x0fToolInfoRequest\x12\x11\n\ttool_name\x18\x01 \x01(\t\"c\n\x08ToolInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\"\n\x06params\x18\x04 \x03(\x0b\x32\x12.agentic.ToolParam\"N\n\tToolParam\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08required\x18\x04 \x01(\x08\x32\xb5\x01\n\x0bToolService\x12:\n\x0b\x45xecuteTool\x12\x14.agentic.ToolRequest\x1a\x15.agentic.ToolResponse\x12.\n\tListTools\x12\x0e.agentic.Empty\x1a\x11.agentic.ToolList\x12:\n\x0bGetToolInfo\x12\x18.agentic.ToolInfoRequest\x1a\x11.agentic.ToolInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tools_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=24
  _globals['_EMPTY']._serialized_end=31
  _globals['_TOOLREQUEST']._serialized_start=33
  _globals['_TOOLREQUEST']._serialized_end=108
  _globals['_TOOLRESPONSE']._serialized_start=110
  _globals['_TOOLRESPONSE']._serialized_end=202
  _globals['_TOOLLIST']._serialized_start=204
  _globals['_TOOLLIST']._serialized_end=248
  _globals['_TOOLINFOREQUEST']._serialized_start=250
  _globals['_TOOLINFOREQUEST']._serialized_end=286
  _globals['_TOOLINFO']._serialized_start=288
  _globals['_TOOLINFO']._serialized_end=387
  _globals['_TOOLPARAM']._serialized_start=389
  _globals['_TOOLPARAM']._serialized_end=467
  _globals['_TOOLSERVICE']._serialized_start=470
  _globals['_TOOLSERVICE']._serialized_end=651
# @@protoc_insertion_point(module_scope)
