# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from server.proto import tools_pb2 as tools__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tools_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ToolServiceStub(object):
    """── Tool Service ────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTool = channel.unary_unary(
                '/agentic.ToolService/ExecuteTool',
                request_serializer=tools__pb2.ToolRequest.SerializeToString,
                response_deserializer=tools__pb2.ToolResponse.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/agentic.ToolService/ListTools',
                request_serializer=tools__pb2.Empty.SerializeToString,
                response_deserializer=tools__pb2.ToolList.FromString,
                _registered_method=True)
        self.GetToolInfo = channel.unary_unary(
                '/agentic.ToolService/GetToolInfo',
                request_serializer=tools__pb2.ToolInfoRequest.SerializeToString,
                response_deserializer=tools__pb2.ToolInfo.FromString,
                _registered_method=True)


class ToolServiceServicer(object):
    """── Tool Service ────────────────────────────────────────────

    """

    def ExecuteTool(self, request, context):
        """Execute a single tool and get result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """List all available tools
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetToolInfo(self, request, context):
        """Get tool metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTool,
                    request_deserializer=tools__pb2.ToolRequest.FromString,
                    response_serializer=tools__pb2.ToolResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=tools__pb2.Empty.FromString,
                    response_serializer=tools__pb2.ToolList.SerializeToString,
            ),
            'GetToolInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToolInfo,
                    request_deserializer=tools__pb2.ToolInfoRequest.FromString,
                    response_serializer=tools__pb2.ToolInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentic.ToolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentic.ToolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolService(object):
    """── Tool Service ────────────────────────────────────────────

    """

    @staticmethod
    def ExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentic.ToolService/ExecuteTool',
            tools__pb2.ToolRequest.SerializeToString,
            tools__pb2.ToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentic.ToolService/ListTools',
            tools__pb2.Empty.SerializeToString,
            tools__pb2.ToolList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetToolInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentic.ToolService/GetToolInfo',
            tools__pb2.ToolInfoRequest.SerializeToString,
            tools__pb2.ToolInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
